---
- name: Deploy
  hosts: proxmox_server

  vars_files: [vars.yml]

  vars:
    assets_path: '{{ playbook_dir }}/assets'
    files_path: '{{ playbook_dir }}/files'
    handlers_path: '{{ playbook_dir }}/handlers'
    tasks_path: '{{ playbook_dir }}/tasks'
    templates_path: '{{ playbook_dir }}/templates'

  tasks:
    - name: SSH
      include_tasks: '{{ tasks_path }}/ssh.yml'
      tags: ssh

    - name: System Hardening
      include_tasks: '{{ tasks_path }}/system_hardening.yml'
      tags: system_hardening

    - name: Base config
      include_tasks: '{{ tasks_path }}/base.yml'
      tags: base

    - name: Install and config fail2ban
      include_tasks: '{{ tasks_path }}/fail2ban.yml'
      tags: fail2ban

    - name: Install and config Chrony
      include_tasks: '{{ tasks_path }}/sntp.yml'
      tags: sntp

    - name: Mound external storages
      include_tasks: '{{ tasks_path }}/external_disks.yml'
      tags: storage

    - name: Hide annoying Subscription Notice
      include_tasks: '{{ tasks_path }}/sub_notice_patch.yml'
      tags: sub_notice_patch

  handlers:
    - name: Restart sshd
      include_tasks: '{{ handlers_path }}/ssh.yml'
      tags: ssh

    - name: Restart fail2ban
      include_tasks: '{{ handlers_path }}/fail2ban.yml'
      tags: fail2ban

    - name: Restart chronyd
      include_tasks: '{{ handlers_path }}/sntp.yml'
      tags: sntp

    - name: Restart pveproxy
      include_tasks: '{{ handlers_path }}/pveproxy.yml'
      tags: sub_notice_patch
