---
- block:
    - name: Disable Enterprise Repos
      replace:
        path: /etc/apt/sources.list.d/{{ enterprise_repo }}.list
        regexp: ^(deb .*enterprise.*)$
        replace: '# \1'
      loop:
        - pve-enterprise
        - ceph
      loop_control:
        loop_var: enterprise_repo
      become: true

    - name: Add No-Subscription Repo
      lineinfile:
        path: /etc/apt/sources.list
        line: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
        insertafter: EOF
        state: present
      become: true

    - name: Uninstall garbage
      apt:
        name:
          - nano
          - vim-*
        state: absent
        purge: true
        autoremove: true
      become: true

    - name: Update deb-based system
      apt:
        name: '*'
        state: latest
        update_cache: true
      become: true

    - name: Install necessary packages
      apt:
        name:
          - bash-completion
          - curl
          - htop
          - neovim
          - tree
        state: latest
        update_cache: true
      become: true

  tags: base
