---
- name: Restart networking service
  service:
    name: networking
    state: restarted
  become: true
  tags: network

- name: Restart Samba
  service:
    name: smbd
    state: restarted
  become: true
  tags: smb

- name: Restart pveproxy
  service:
    name: pveproxy
    state: restarted
  become: true
  tags: [sub_notice_patch, pve_hardening]

- name: Restart Proxmox web proxy
  service:
    name: '{{ proxmox_web_proxy_service }}'
    state: restarted
  become: true
